services:
    - type: web
    name: truthtvug
    env: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
            - path: /sw.js
        name: Service-Worker-Allowed
        value: /
